Repository nephio-project/free5gc, pull requests merged in 2023-04, with the labels that each got.

#4 Add initial implementation of the operator and UPFDeployment controller
  free5gc-operator/.dockerignore
  free5gc-operator/.gitignore
  free5gc-operator/Dockerfile
  free5gc-operator/Makefile
  free5gc-operator/PROJECT
  free5gc-operator/README.md
  free5gc-operator/api/v1alpha1/groupversion_info.go
  free5gc-operator/api/v1alpha1/upfdeployment_types.go
  free5gc-operator/api/v1alpha1/zz_generated.deepcopy.go
  free5gc-operator/config/crd/bases/workload.nephio.org_upfdeployments.yaml
  free5gc-operator/config/crd/kustomization.yaml
  free5gc-operator/config/crd/kustomizeconfig.yaml
  free5gc-operator/config/crd/patches/cainjection_in_upfdeployments.yaml
  free5gc-operator/config/crd/patches/webhook_in_upfdeployments.yaml
  free5gc-operator/config/default/kustomization.yaml
  free5gc-operator/config/default/manager_auth_proxy_patch.yaml
  free5gc-operator/config/default/manager_config_patch.yaml
  free5gc-operator/config/manager/kustomization.yaml
  free5gc-operator/config/manager/manager.yaml
  free5gc-operator/config/prometheus/kustomization.yaml
  free5gc-operator/config/prometheus/monitor.yaml
  free5gc-operator/config/rbac/auth_proxy_client_clusterrole.yaml
  free5gc-operator/config/rbac/auth_proxy_role.yaml
  free5gc-operator/config/rbac/auth_proxy_role_binding.yaml
  free5gc-operator/config/rbac/auth_proxy_service.yaml
  free5gc-operator/config/rbac/kustomization.yaml
  free5gc-operator/config/rbac/leader_election_role.yaml
  free5gc-operator/config/rbac/leader_election_role_binding.yaml
  free5gc-operator/config/rbac/role.yaml
  free5gc-operator/config/rbac/role_binding.yaml
  free5gc-operator/config/rbac/service_account.yaml
  free5gc-operator/config/rbac/upfdeployment_editor_role.yaml
  free5gc-operator/config/rbac/upfdeployment_viewer_role.yaml
  free5gc-operator/config/samples/workload_v1alpha1_upfdeployment.yaml
  free5gc-operator/controllers/free5gc_upf_wrapper.go
  free5gc-operator/controllers/free5gc_upfcfg.go
  free5gc-operator/controllers/suite_test.go
  free5gc-operator/controllers/upfdeployment_controller.go
  free5gc-operator/controllers/upfdeployment_controller_test.go
  free5gc-operator/go.mod
  free5gc-operator/go.sum
  free5gc-operator/hack/boilerplate.go.txt
  free5gc-operator/main.go
  free5gc-operator/test/nad-test.yaml
  free5gc-operator/test/nad/upf-n3-nad.yaml
  free5gc-operator/test/nad/upf-n3-nad2.yaml
  free5gc-operator/test/nad/upf-n4-nad.yaml
  free5gc-operator/test/nad/upf-n4-nad2.yaml
  free5gc-operator/test/nad/upf-n6-nad.yaml
  free5gc-operator/test/nad/upf-n6-nad2.yaml
  free5gc-operator/test/test-nad.yaml
  free5gc-operator/test/upfdeploy.yaml
  free5gc-operator/test/upfdeploy2.yaml
Labels: approved, lgtm

#5 Modified Makefile and .prow.yaml to run golangci-lint, gosec and unit…
  .prow.yaml
  free5gc-operator/Makefile
Labels: approved, lgtm, ok-to-test

#8 Prow job update, license header checking added
  .prow.yaml
Labels: approved, lgtm, needs-ok-to-test

#12 UPFDeployment align with nephio-project/api/nf_deployments/v1alpha1
  free5gc-operator/Makefile
  free5gc-operator/PROJECT
  free5gc-operator/api/v1alpha1/groupversion_info.go
  free5gc-operator/api/v1alpha1/upfdeployment_types.go
  free5gc-operator/api/v1alpha1/zz_generated.deepcopy.go
  free5gc-operator/config/crd/bases/workload.nephio.org_upfdeployments.yaml
  free5gc-operator/config/rbac/role.yaml
  free5gc-operator/controllers/free5gc_upf_wrapper.go
  free5gc-operator/controllers/free5gc_upfcfg.go
  free5gc-operator/controllers/suite_test.go
  free5gc-operator/controllers/upfdeployment_controller.go
  free5gc-operator/controllers/upfdeployment_controller_test.go
  free5gc-operator/controllers/utils.go
  free5gc-operator/controllers/utils_test.go
  free5gc-operator/go.mod
  free5gc-operator/go.sum
  free5gc-operator/main.go
  free5gc-operator/test/upfdeploy.yaml
  free5gc-operator/test/upfdeploy2.yaml
Labels: approved, lgtm
